config/routes.rb
Rails.application.routes.draw do
  root to: 'stories#index'

  get 'news', to: 'stories#index', category: 'news'
  get 'newest', to: 'stories#index', category: 'newest'
  get 'show', to: 'stories#index', category: 'show'
  get 'ask', to: 'stories#index', category: 'ask'
  get 'jobs', to: 'stories#index', category: 'jobs'

  resources :stories, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < Item
  def initialize(attributes)
    super attributes

    return unless comments

    self.comments = comments.map do |comment|
      Comment.new comment
    end
  end

  def cache_key
    "comments/#{hash}"
  end
end

app/models/item.rb
class Item
  include ActiveModel::Model

  attr_accessor :id, :title, :points, :user, :time, :time_ago, :type, :content, :dead, :deleted, :comments, :comments_count, :level, :url, :domain, :hash

  def initialize(attributes)
    super attributes

    self.hash = JSON.generate attributes
  end
end

app/models/story.rb
class Story < Item
  def initialize(attributes)
    super attributes

    return unless comments

    self.comments = comments.map do |comment|
      Comment.new comment
    end
  end

  def cache_key
    "stories/#{hash}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
require 'open-uri'

class StoriesController < ApplicationController
  def index
    @stories = HackerNewsAPI.new(story_params).stories
  end

  def show
    @story = HackerNewsAPI.new(story_params).story
  end

  private

  def story_params
    params.permit :category, :page, :id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_page
    params[:page] || 1
  end

  def current_category
    params[:category] || 'news'
  end

  def first_page?
    current_page.to_i == 1
  end

  def previous_page_path
    current_path.merge page: current_page.to_i - 1
  end

  def next_page_path
    current_path.merge page: current_page.to_i + 1
  end

  private

  def current_path
    params.permit(:category, :page).merge category: current_category
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def domain(url)
    URI(url).host.gsub(/www\./, '') rescue ''
  end
end

app/views/comments/_comment.html.erb
<li>
  <small class="gray"><%= comment.by %></small>
  <p><%= sanitize comment.text %></p>
  <ul><%= render comment.comments, cached: true %></ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hacker News</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A Hacker News PWA made with Ruby on Rails.">
    <meta name="theme-color" content="#ffffff">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', async: true %>
    <link rel="manifest" href="/manifest.json" />
    <style>
      body {
        color: #333;
        padding: 3.34em 1em 0 1em;
        margin: 0;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
        font-size: 16px;
        line-height: 22px;
      }

      p, ol, ul, td {
        font-size: 16px;
        line-height: 22px;
      }

      ul, ol {
        list-style: none;
      }

      h2 {
        margin-bottom: .5em;
      }

      ol {
        margin: 0;
        padding-left: 0;
      }

      ul {
        padding-left: 1.34em;
      }

      li {
        margin-top: 1.34em;
        margin-bottom: 1.34em;
      }

      pre {
        background-color: #eee;
        padding: 10px;
        font-size: 13px;
      }

      a {
        color: #333;
      }

      a:visited {
        color: #777;
      }

      a:hover {
        color: #fff;
        background-color: #333;
      }

      .gray {
          color: #777;
      }

      .mt-1 {
        margin-top: 1.34em;
      }

      .animated {
        animation-timing-function: cubic-bezier(.55, 0, .1, 1);
        animation-duration: 150ms;
        animation-fill-mode: both;
      }

      @keyframes fadeOutLeft {
        from {
          opacity: 1;
        }

        to {
          opacity: 0;
          transform: translate3d(-1em, 0, 0);
        }
      }

      .fadeOutLeft {
        animation-name: fadeOutLeft;
      }

      @keyframes fadeInRight {
        from {
          opacity: 0;
          transform: translate3d(1em, 0, 0);
        }

        to {
          opacity: 1;
          transform: none;
        }
      }

      .fadeInRight {
        animation-name: fadeInRight;
      }

      .turbolinks-progress-bar {
        top: calc(3.34em - 1px);
        height: 2px;
        background-color: #777;
        width: 100%;
      }

      .navbar-brand {
        font-family: georgia;
        display: inline-block;
      }

      .navbar {
        position: fixed;
        top: 0;
        left: 0;
        padding: 0 1em;
        width: calc(100% - 2em);
        background-color: #fff;
        border-bottom: 1px solid #ddd;
        z-index: 2;
      }

      .navbar-nav {
        display: inline-block;
        float: right;
        width: auto;
        margin: 1em 0;
      }

      h3 {
        font-size: 1em;
      }

      .pl-0 {
        padding-left: 0;
      }

      #content {
        animation-timing-function: cubic-bezier(.55, 0, .1, 1);
        animation-duration: 150ms;
        animation-fill-mode: both;
      }

      .active {
        pointer-events: none;
        text-decoration: none;
      }
    </style>
  </head>
  <body>
    <nav class="navbar">
      <h3 class="navbar-brand">HN</h3>
      <div class="navbar-nav">
        <%= active_link_to "Top", news_path %> |
        <%= active_link_to "New", newest_path %> |
        <%= active_link_to "Ask", ask_path %> |
        <%= active_link_to "Show", show_path %> |
        <%= active_link_to "Jobs", jobs_path %>
      </div>
    </nav>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/stories/_story.html.erb
<li>
  <div>
    <%= link_to story.title, story.url %>
    <% if story.url %>
      <small><em class="gray">(<%= domain(story.url) %>)</em></small>
    <% end %>
  </div>

  <small class="gray">
    <%= pluralize story.score, 'point' %> -
    <%= story.by %>
    <% if story.descendants %>
      - <%= link_to pluralize(story.descendants, 'comment'), story_path(story.id), class: 'gray' %>
    <% end %>
  </small>
</li>

app/views/stories/index.html.erb
<ol><%= render @stories, cached: true %></ol>

<span class="gray"><%= link_to_unless first_page?, "Prev", previous_page_path %></span> |
<%= link_to "Next", next_page_path %>

app/views/stories/show.html.erb
<div class="mt-1">
  <%= link_to @story.title, @story.url %>
  <% if @story.url %>
    <small><em class="gray">(<%= domain(@story.url) %>)</em></small>
  <% end %>
</div>

<small class="gray">
  <%= pluralize @story.score, 'point' %> -
  <%= @story.by %>
  <% if @story.descendants %>
    - <%= pluralize(@story.descendants, 'comment') %>
  <% end %>
</small>

<ul class="pl-0"><%= render @story.comments, cached: true %></ul>